server.port: 8799
spring:
  profiles:
    active: after_route

---
profiles: after_route
spring:
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://localhost:8765
        predicates:
        - After=2021-09-11T00:00:00.000-07:00[Asia/Shanghai]
